name: Go CI (BigQuery Mock Test)

on:
  push:
    branches:
      - main # ✅ main 브랜치에 push 시 실행
  pull_request:
    branches:
      - main # ✅ main 브랜치로 PR 발생 시 실행

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2. 필수 패키지 설치 (g++-12, clang)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++-12 clang make

      # ✅ 3. Go 설치
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      # ✅ 4. 환경 변수 설정
      - name: Set environment variables
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CXX=g++-12" >> $GITHUB_ENV
          echo "CC=gcc-12" >> $GITHUB_ENV

      # ✅ 5. 의존성 설치 및 캐싱
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: |
          go mod tidy
          go mod download
          go install ./...

      # ✅ 6. 코드 빌드
      - name: Build
        run: go build ./...

      # ✅ 7. 테스트 실행
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -v

      # ✅ 8. 코드 커버리지 출력
      - name: Show coverage result
        run: go tool cover -func=coverage.out
