name: Go CI (BigQuery Mock Test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (GCC, Clang)
        run: |
          sudo apt update
          sudo apt install -y g++-12 gcc-12 clang make

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set environment variables
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CC=gcc-12" >> $GITHUB_ENV
          echo "CXX=g++-12" >> $GITHUB_ENV
          echo "CXXFLAGS=-Wno-macro-redefined -Wno-unknown-warning-option" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-Wl,--allow-multiple-definition" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: |
          go mod tidy
          go mod download
          go install ./...

      - name: Build
        run: |
          CGO_LDFLAGS="-Wl,--allow-multiple-definition" go build ./...

      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -v

      - name: Show coverage result
        run: go tool cover -func=coverage.out
